name: CI
on:
  push:
    branches: [ "master" ]
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: ubuntu-latest
    #steps:
    #- name: Setup Ninja
    #  uses: ashutoshvarma/setup-ninja@master
    #  with:
    #    # ninja version to download. Default: 1.10.0
    #    version: 1.10.0
    - uses: actions/checkout@v4
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ..
        cmake --build . --config ${{env.BUILD_TYPE}} 
        ctest -C ${{env.BUILD_TYPE}}
