name: CI

on: 
  push:
  pull_request:

env:
  BUILD_TYPE: Release
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@main
      with:
        access_token: ${{ secrets.TOKEN }}
    - uses: actions/checkout@v4
    - name: "Get file config"
      run: |
        curl -H "Accept: application/vnd.github.VERSION.raw" -H "Authorization: token ${{ secrets.TOKEN }}" https://api.github.com/repos/Geode-solutions/actions/contents/.clang-format\?ref\=master > .clang-format
    - uses: DoozyX/clang-format-lint-action@master
      with:
        extensions: "h,cpp"
        clangFormatVersion: 14
        inplace: True
    - uses: stefanzweifel/git-auto-commit-action@v5
      id: commit
      with:
        commit_message: Apply format changes

  build:
    runs-on: ubuntu-latest
    needs: [format]
    steps:
    - uses: actions/checkout@v4
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ..
        cmake --build . --config ${{env.BUILD_TYPE}} 
        ctest -C ${{env.BUILD_TYPE}}


  semantic-release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      with:
        branches: 'master'
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}